addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype" % "3.9.5")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"      % "2.1.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"      % "1.0.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"  % "0.5.1")
addSbtPlugin("com.dwijnand"     % "sbt-dynver"   % "4.1.1")
addSbtPlugin("ch.epfl.lamp"     % "sbt-dotty"    % "0.5.2")
