addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype" % "3.9.5")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"      % "2.0.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"      % "1.0.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"  % "0.5.1")
addSbtPlugin("com.dwijnand"     % "sbt-dynver"   % "4.1.1")
